select
    vendor_id,
    pickup_datetime,
    dropoff_datetime,
    pickup_datetime::date                   as pickup_date,
    extract(hour from pickup_datetime)::int as pickup_hour,
    pickup_location_id,
    dropoff_location_id,
    payment_type,
    rate_code_id,
    store_and_fwd_flag,
    passenger_count,
    passenger_count_missing,
    zero_distance,
    trip_distance,
    trip_duration_minutes,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    improvement_surcharge,
    congestion_surcharge,
    airport_fee,
    cbd_congestion_fee,
    total_amount,
    pickup_borough,
    pickup_zone,
    dropoff_borough,
    dropoff_zone,
    year,
    month
from {{ source('staging', 'yellow_trips') }}
